name: test
on:
  pull_request:
  push:
    branches: [main]
jobs:
  suite:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: node --test --experimental-test-coverage
  test:
    needs: [suite]
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
